// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stefan.Server.Infrastructure;

#nullable disable

namespace Stefan.Server.Infrastructure.Migrations.StefanDb
{
    [DbContext(typeof(StefanDbContext))]
    [Migration("20260610211830_InitialDatabaseCreate")]
    partial class InitialDatabaseCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stefan.Server.Domain.CommandRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<byte[]>("InputAudio")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<double>("InputAudioDurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("InputAudioFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LlmConversationJson")
                        .HasColumnType("text");

                    b.Property<double?>("LlmDurationMs")
                        .HasColumnType("double precision");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("OutputAudio")
                        .HasColumnType("bytea");

                    b.Property<string>("OutputAudioFormat")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseText")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("SttDurationMs")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalDurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("Transcript")
                        .HasColumnType("text");

                    b.Property<double?>("TtsDurationMs")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CommandRecords");
                });

            modelBuilder.Entity("Stefan.Server.Domain.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastKnownIpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestartCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Stefan.Server.Domain.NodeStatusReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("double precision");

                    b.Property<double?>("DiskUsage")
                        .HasColumnType("double precision");

                    b.Property<string>("GitCommit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("NodeStatusReports");
                });
#pragma warning restore 612, 618
        }
    }
}
